name: Build and Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_NAME: WindowControlEx
      VERSION: 1.3.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cmake --build build --config Release
        shell: bash

      - name: Prepare package directory
        run: |
          mkdir release
          cp build/bin/Release/WindowControlEx.exe release/
          cp blocklist.json release/
          cp config.json release/
        shell: bash

      - name: Create zip archive
        run: |
          cd release
          7z a ../${{ env.PROJECT_NAME }}-Windows-${{ env.VERSION }}-x86_64.zip *
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-Windows-x86_64
          path: ${{ env.PROJECT_NAME }}-Windows-${{ env.VERSION }}-x86_64.zip
